name: Fetch Matches Data

on:
  schedule:
    - cron: '0 9 * * *'  # كل يوم الساعة 09:00 صباحًا بالتوقيت العالمي
  push:
    branches:
      - main

jobs:
  fetch-matches:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run fetch script
      run: |
        python scripts/fetch_matches.py
